/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.presentation.views;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

//importando a classe de exeção das variaveis do menu
import src.shared.Cadastros_Exption;

//importando a classe para usar a exeção de img
import src.shared.Selecionar_Img_Exption;

/**
 *
 * @author Rafael Martins
 */
public class Cadastros extends javax.swing.JFrame {
    
    private String url_imagem=null;
    
        //métodos gets and setts da imagem

            public String getUrl_imagem() {
                return url_imagem;
            }

            public void setUrl_imagem(String url_imagem) {
                this.url_imagem = url_imagem;
            }
        
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastros.class.getName());

    /**
     * Creates new form Interface
     */
    public Cadastros() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_Nome_Produto = new javax.swing.JTextField();
        jTextField1_Preço_Produto = new javax.swing.JTextField();
        jTextField2_Quantidade_em_Estoque = new javax.swing.JTextField();
        jButton1_Cadastrar = new javax.swing.JButton();
        jButton1_selecionar_Imagem = new javax.swing.JButton();
        jButton1_Cancelar = new javax.swing.JButton();
        jLabel6_Imagem_Produto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastros");

        jLabel1.setText("Nome:");

        jLabel2.setText("Preço:");

        jLabel3.setText("Quantidade em Estoque:");

        jTextField1_Nome_Produto.setToolTipText("Insira o nome do Produto");

        jTextField1_Preço_Produto.setToolTipText("Inserira o preço do produto");

        jTextField2_Quantidade_em_Estoque.setToolTipText("Insira a quantidade em estoque");

        jButton1_Cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButton1_Cadastrar.setText("Cadastrar");
        jButton1_Cadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_Cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_CadastrarActionPerformed(evt);
            }
        });

        jButton1_selecionar_Imagem.setText("Selecionar Imagem...");
        jButton1_selecionar_Imagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_selecionar_ImagemActionPerformed(evt);
            }
        });

        jButton1_Cancelar.setForeground(new java.awt.Color(255, 51, 51));
        jButton1_Cancelar.setText("Cancelar");
        jButton1_Cancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1_Cancelar.setMaximumSize(new java.awt.Dimension(54, 20));
        jButton1_Cancelar.setMinimumSize(new java.awt.Dimension(54, 20));

        jLabel6_Imagem_Produto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1_Preço_Produto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1_Nome_Produto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2_Quantidade_em_Estoque))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6_Imagem_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_selecionar_Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jButton1_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jButton1_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_Nome_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_Preço_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2_Quantidade_em_Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addComponent(jLabel6_Imagem_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1_selecionar_Imagem)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_selecionar_ImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_selecionar_ImagemActionPerformed
       
        
        JFileChooser jFileChooser=new JFileChooser();
        FileNameExtensionFilter filtado=new FileNameExtensionFilter("JPG , PNG & GIF", "JPG","PNG","GIF");
        jFileChooser.setFileFilter(filtado);
        
        int IMG_Mostrar=jFileChooser.showOpenDialog(this);
        
        if (IMG_Mostrar == JFileChooser.APPROVE_OPTION) {
        url_imagem = jFileChooser.getSelectedFile().getPath();

        // Redimensiona a imagem de acordo com o tamanho do JLabel
        ImageIcon icon = new ImageIcon(new ImageIcon(url_imagem).getImage()
                .getScaledInstance(jLabel6_Imagem_Produto.getWidth(), jLabel6_Imagem_Produto.getHeight(), Image.SCALE_SMOOTH));

        jLabel6_Imagem_Produto.setIcon(icon); // exibe a imagem no JLabel
    }
    }//GEN-LAST:event_jButton1_selecionar_ImagemActionPerformed

    //Adicionando uma Action para verificar os dados na hora do Cadastro
    private void jButton1_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_CadastrarActionPerformed
       //Tranformando o TextFile em Sting
       
       try {
           
           //validação da imagem
          //criando um classe para isso
         //chamando método para isso
         Selecionar_Img_Exption selecionar=new Selecionar_Img_Exption();
         selecionar.validarImagem(url_imagem);
          
           
            String nome = jTextField1_Nome_Produto.getText();
            String preco = jTextField1_Preço_Produto.getText();
            String qtdEstoque = jTextField2_Quantidade_em_Estoque.getText();

            Cadastros_Exption validar = new Cadastros_Exption();
            validar.ValidarCadastro(nome, preco, qtdEstoque);

            double precoD = Double.parseDouble(preco);
            int qtd_estoque = Integer.parseInt(qtdEstoque);

            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Cadastrar;
    private javax.swing.JButton jButton1_Cancelar;
    private javax.swing.JButton jButton1_selecionar_Imagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6_Imagem_Produto;
    private javax.swing.JTextField jTextField1_Nome_Produto;
    private javax.swing.JTextField jTextField1_Preço_Produto;
    private javax.swing.JTextField jTextField2_Quantidade_em_Estoque;
    // End of variables declaration//GEN-END:variables
}
