/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.presentation.views;

/**
 *
 * @author Rafael Martins
 */
public class Tela_Inicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela_Inicial.class.getName());

    /**
     * Creates new form Interface
     */
    public Tela_Inicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_Cadastros = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2_Vendas = new javax.swing.JMenu();
        jMenuItem3_Venda = new javax.swing.JMenuItem();
        jMenu3_Relatorios = new javax.swing.JMenu();
        jMenuItem3_Relatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jMenu1_Cadastros.setText("Produtos");

        jMenuItem1.setText("Cadastros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem1);

        jMenuItem2.setText("Cadastrados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1_Cadastros.add(jMenuItem2);

        jMenuBar1.add(jMenu1_Cadastros);

        jMenu2_Vendas.setText("Vendas");

        jMenuItem3_Venda.setText("Vendas");
        jMenuItem3_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_VendaActionPerformed(evt);
            }
        });
        jMenu2_Vendas.add(jMenuItem3_Venda);

        jMenuBar1.add(jMenu2_Vendas);

        jMenu3_Relatorios.setText("Relatórios");

        jMenuItem3_Relatorio.setText("Relatorios");
        jMenuItem3_Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_RelatorioActionPerformed(evt);
            }
        });
        jMenu3_Relatorios.add(jMenuItem3_Relatorio);

        jMenuBar1.add(jMenu3_Relatorios);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Cadastros().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Alterações().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_VendaActionPerformed
        new Vendas().setVisible(true);
    }//GEN-LAST:event_jMenuItem3_VendaActionPerformed

    private void jMenuItem3_RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_RelatorioActionPerformed
         new Relatorios().setVisible(true);
    }//GEN-LAST:event_jMenuItem3_RelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1_Cadastros;
    private javax.swing.JMenu jMenu2_Vendas;
    private javax.swing.JMenu jMenu3_Relatorios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3_Relatorio;
    private javax.swing.JMenuItem jMenuItem3_Venda;
    // End of variables declaration//GEN-END:variables
}
